### ISSUE TITLE
Garbage collection not working on a multiste WordPress

### ISSUE THREAD

**Issue by druellan** [pantheon-systems/wp-native-php-sessions#102]
Hi!
I'm in the process of cleanup a project deployed a couple of years ago. It is a multisite, multilang (Polylang) site, and something that caught my attention was the size of the sessions tables:

![2018-08-07_15h52_57](https://user-images.githubusercontent.com/6965667/43841683-1905ed06-9afa-11e8-8e5d-5bb3df45d1b2.png)

Seems that the garbage collector is not working properly. I wonder if anyone has some advice to where to start checking: perhaps the multisite is interfering, or perhaps I need to make sure the sessions are actually being closed in the code?

Thanks!

**Comment by danielbachhuber** [comment]
Hi @druellan,

Here's the corresponding garbage collection code:

https://github.com/pantheon-systems/wp-native-php-sessions/blob/0ab0a2360dc51b5a777195f1cf1f03eb96f91b56/callbacks.php#L152-L162

Can you check to see if `gc_maxlifetime` might be set somewhere in your codebase?

**Comment by druellan** [comment]
Thanks @danielbachhuber I'm going to check the code later in the week, but checking the datetime as you suggested, I can see that everything is marked as NULL on the bigger table, so that might be the problem.

I'm going to try and update the table with an old date to see if the garbage collector works as expected.

**Comment by danielbachhuber** [comment]
@druellan Were you able to track down additional detail here?

**Comment by druellan** [comment]
Oh, sorry the delay. I could not, because it was imperative to fix the problem, so, I just did a wipe of the tables, but I can confirm that new sessions created (tested on both a development and staging servers) have the correct timestamp, so, I'm unsure why that was not working correctly.

About the correct operation of the garbage collector, I'm going to keep an eye while the site is in use, to see if the tables keep growing. We have a deploy today, and I'm going to peek the tables on the staging server.

Just as a trivia, at the moment of the wipe, we had:
Main site - ~1.600.000 rows
Multisite 2 - ~90.000 rows
Multisite 3 - ~108.000 rows
Multisite 4 - 66.00 rows
Multisite 5 - 50.000 rows

Backup size before the wipe: ~740 megabytes
Backup size after the wipe: ~70 megabytes

**Comment by danielbachhuber** [comment]
Sounds good, thanks!
