### ISSUE TITLE
Ensure `$wpdb` object is available when writing a session on `session_write_close`

### ISSUE THREAD

**Issue by danielbachhuber** [pantheon-systems/wp-native-php-sessions#103]
There have been at least a few reports of fatal errors because `$wpdb` isn't available in our `session_write_close` callback. For instance:

> I’ve done some investigation on the incompatibilities. The biggest problem is that Bookly decides to wait until objects are destructed to persist anything to the session (See `Bookly\Lib\UserBookingData` and the `destruct` method). By that logic, and from what I have seen, the custom session handler is going to be already destroyed by the time the plugin tries to write data to the session.

From https://wordpress.org/support/topic/pantheon-wp-native-sessions-and-bookly/
#49 is also a past thread.

We should identify some solution for this.

**Comment by greg-1-anderson** [comment]
If a shutdown handler adds a shutdown handler, then the newly-added shutdown handler will run after all of the shutdown handlers that were added before it. This is probably the right technique to use for `session_write_close`, as you can then postpone writing the session data until all other plugins are finished using the session.

**Comment by greg-1-anderson** [comment]
Hm actually `$wpdb` is destroyed in a shutdown handler as well, isn't it? I suppose there's no getting around re-instantiating the database connection.
