### ISSUE TITLE
Warning Message: session_id()

### ISSUE THREAD

**Issue by elvc** [pantheon-systems/wp-native-php-sessions#118]
Hello,

I am getting a warning on one of my multidev environment on my client's site, but it's not happening on the live site:
```
Warning: session_id(): Cannot change session id when session is active in /srv/bindings/52f9f363345f423db65e0b839ba4cfd0/code/wp-content/plugins/wp-native-php-sessions/callbacks.php on line 34
```
This is not affecting my live site as I have not deployed it yet, but it also means I am blocked by it and nothing can be deployed.

System Info:
WordPress - Version 5.2.1
Native PHP Sessions for WordPress - Version 0.7.0

Thanks in advance.

**Comment by ataylorme** [comment]
@elvc what PHP version are you using? If you are using PHP `7.3` can you try rolling back to PHP `7.2` or `7.1`?

**Comment by elvc** [comment]
@ataylorme We are running 7.3 on development, test, and live environment on Pantheon, but only development has this issue, which is strange.

I also tried branching off from production and push to a dev environment on Pantheon without any code changes. For some reason it shows the warning.

**Comment by ataylorme** [comment]
@elvc does the warning still continue when you test on a dev environment with PHP `7.2` or `7.1`?

**Comment by elvc** [comment]
I have not done the rollback to test because we need to be on 7.3 anyway on production. Is this a known issue with 7.3?

**Comment by ataylorme** [comment]
I searched our support tickets and found one other instance and that fixed it for them.

I’m hoping you can confirm so we know if it is an issue and can start exploring a fix

**Comment by danielbachhuber** [comment]
@elvc I worked with another Pantheon customer on what I think is the same issue a couple weeks ago. Here's what [I found to be the resolution](https://wordpress.org/support/topic/session_id-warning/#post-11722017):

> The specific problem in this case is that some other plugin is starting a session before WP Native PHP Sessions is loaded.
> 
> To fix the issue, I created a mu-plugin (wp-content/mu-plugins/wpnps-loader.php) to load WP Native PHP Sessions earlier than all of the other plugins:
> 
> ```
> <?php
> require_once WP_PLUGIN_DIR . '/wp-native-php-sessions/pantheon-sessions.php';
> ```

The underlying problem does exist in PHP 7.2 — PHP 7.3 just started emitting a more visible warning for it.

Hope this helps clarify! Feel free to include any further questions you might have.

**Comment by jcady13** [comment]
Hello @danielbachhuber I'm having similar issues and was lead here by Pantheon support. I tried creating a file with your same name in the exact location you noted and pushed it live, but I'm getting the same "Cannont change session id when session is active" PHP Warning every 5-30 seconds. Is there something I'm missing with this fix? Thank you!

**Comment by danielbachhuber** [comment]
@jcady13 It's hard to say without looking at the codebase. Can you shoot me an email (address is on my GitHub profile) and we can chat further?

**Comment by danielbachhuber** [comment]
Re-opening this because I've come across another report where:
1. WPNPS is correctly loaded as a mu-plugin.
2. The theme is calling `session_start()` at the top of its `functions.php` file.
3. We're still seeing the `Warning: session_id(): Cannot change session id when session is active in /srv/bindings/aaaaaaaaa/code/wp-content/mu-plugins/wp-native-php-sessions/callbacks.php on line 39` error.

My earlier assumptions might've been incorrect!

It looks like the offending code moved to `_pantheon_session_open()` in #17. Drupal 7 was our original reference for WP Native PHP Sessions, and its session implementation is quite different: https://git.drupalcode.org/project/drupal/blame/7.x/includes/session.inc I think I need to spend some time reconciling the two.

**Comment by danielbachhuber** [comment]
@elvc @jcady13 Would either/both of you be willing to [test out 0.9.0-alpha1](https://downloads.wordpress.org/plugin/wp-native-php-sessions.zip) on your site, which fixes the issue, to verify everything still works as expected? My tests all pass but it'd be great to get some more eyes on it before I tag a release. Thanks 😄

**Comment by danielbachhuber** [comment]
I've tagged the v0.9.0 release. Feel free to open a new GitHub issue if you come across any other funniness to report.
