### ISSUE TITLE
error on the first load of any pages

### ISSUE THREAD

**Issue by AnthoRdev** [pantheon-systems/wp-native-php-sessions#128]
Hello,

I get this error on the first load of any pages of my website : 
`Warning: session_id(): Cannot change session id when session is active in /srv/bindings .wp-content/mu-plugins/wp-native-php-sessions/callbacks.php on line 39`

The site is hosted on Pantheon.
Wordpress v5.2.2
wp-native-php-sessions v0.8.1
PHP 7.3

Is there a solution for that?
Thanks for your help,
Anthony.

**Comment by AnthoRdev** [comment]
Tried that https://github.com/pantheon-systems/wp-native-php-sessions/issues/118#issuecomment-514283831 but doesn't resolve my problem.

**Comment by danielbachhuber** [comment]
Hi @AnthoRdev,

Can you email the address on my GitHub profile? Happy to help you debug there.

Thanks
