### ISSUE TITLE
Plugin Activation Error

### ISSUE THREAD

**Issue by magedmoh94** [pantheon-systems/wp-native-php-sessions#131]
I have tried to install the plugin with wordpress 5.2.2 and got this message the first time activating the plugin

**The plugin generated 254 characters of unexpected output during activation. If you notice “headers already sent” messages, problems with syndication feeds or other issues, try deactivating or removing this plugin.**

**Comment by danielbachhuber** [comment]
Hi @magedmoh94,

If you're seeing errors upon activation, you'll want to [install the plugin as a mu plugin](https://github.com/pantheon-systems/wp-native-php-sessions#troubleshooting).

**Comment by magedmoh94** [comment]
i'm sorry but i don't have a mu-plugin folder inside the wp-content so can you tell me the steps to solve this and how to install it as a mu-plugin.

Also i want to say that this message appears only on the activation but the plugin is activated already ..

**Comment by magedmoh94** [comment]
solved thank you, but the plugin name missing the word -master, update the comment.

And thank you for your fast response

**Comment by magedmoh94** [comment]
I have the plugin deactivated on the plugins list in the wordpress admin panel but its working as i have the tab sessions in the tools, i activated it by the mu-plugins folder run remotely through a php as you mentioned before so is it normal to appear in the plugins list on the dashboard but deactivated ?

**Comment by danielbachhuber** [comment]
> i activated it by the mu-plugins folder run remotely through a php as you mentioned before so is it normal to appear in the plugins list on the dashboard but deactivated ?

Yep. It's fine that it appears as deactivated in the plugins list as long as its loaded as a mu-plugin. You're welcome to activate it too — shouldn't make much of a difference.

**Comment by magedmoh94** [comment]
Thank you for your support :)
