### ISSUE TITLE
Make it more obvious that WP Native PHP Sessions should be loaded as a mu-plugin

### ISSUE THREAD

**Issue by danielbachhuber** [pantheon-systems/wp-native-php-sessions#132]
We've had several reports of PHP error notices exposed by users updating to PHP 7.3: https://github.com/pantheon-systems/wp-native-php-sessions/issues/118#issuecomment-514283831 #128 #130 The underlying issue is that some plugin is starting a PHP session before WP Native PHP Sessions is loaded.

At this point, we should probably strongly recommend that WP Native PHP Sessions should be loaded as a mu-plugin in a couple of ways:

* [ ] Document mu-plugin installation more prominently in the README.
* [ ] Display a dismissable admin notice when we detect WPNPS isn't loaded as a mu-plugin.

**Comment by danielbachhuber** [comment]
@ataylorme I think I might actually hold off on this, given the real problem was #135 (and would occur even if you had WPNPS loaded as a mu-plugin). If it's not actually a hard need, we might cause more support burden than we want by introducing a new admin notice.

**Comment by ataylorme** [comment]
@danielbachhuber sounds good. I am okay with closing this for now and re-opening if needed in the future

**Comment by Julix91** [comment]
My issue ( https://github.com/pantheon-systems/wp-native-php-sessions/issues/144 ) is also after updating PHP (from 7.0 to 7.1 was fine, 7.2 is where it goes wonky) -- However, WPNPS was already being loaded as mu-plugin already, still having issue.
