### ISSUE TITLE
Share session across multisites

### ISSUE THREAD

**Issue by Erwinh** [pantheon-systems/wp-native-php-sessions#147]
Is it possible to share the sessions across multiple sites?

In the current situation, sessions are stored per site in separate tables. Example: wp_pantheon_sessions, wp_2_pantheon_sessions, wp_3_pantheon_sessions ...

**Comment by danielbachhuber** [comment]
Hi @Erwinh,

Thanks for reaching out.

> Is it possible to share the sessions across multiple sites?

This isn't something we formally support but, as you've noticed, it might be as easy as forcing each site to use the same database table. In skimming through the codebase, it doesn't seem like there would be any more than that.
