### ISSUE TITLE
BLOB instead of TEXT?

### ISSUE THREAD

**Issue by jsmoriss** [pantheon-systems/wp-native-php-sessions#15]
Any reason for using a BLOB field type for data instead of TEXT? If the data field was TEXT, it would be editable in phpmyadmin (granted it's serialized, so you have to know what you're doing). ;-)

Thanks,

js.

**Comment by danielbachhuber** [comment]
> Any reason for using a BLOB field type for data instead of TEXT?

No specific reason, other than BLOB is what Drupal uses
