### ISSUE TITLE
There has been a critical error on your website. Please check your site admin email inbox for instructions.

### ISSUE THREAD

**Issue by rsraz** [pantheon-systems/wp-native-php-sessions#160]
Hi! I followed your troubleshooting for the "Warning: ini_set(): A session is active.", then you likely have a plugin that is starting a session before WP Native PHP Sessions is loading.

```
To fix, create a new file at wp-content/mu-plugins/000-loader.php and include the following:
<?php
require_once WP_PLUGIN_DIR . '/wp-native-php-sessions/pantheon-sessions.php';
```

Since I don't have the directory I just made the mu-plugins directory and added a file named "000-loader.php" and entered the code snippet but after that I am already locked out from the site. Please help. What can I do? I just followed your instruction.

**Comment by danielbachhuber** [comment]
@rsraz The contents of the file should be:

```php
<?php
require_once WP_PLUGIN_DIR . '/wp-native-php-sessions/pantheon-sessions.php';
```

The fatal error is likely because of your extra 'To fix, create a new file at wp-content/mu-plugins/000-loader.php and include the following:' in the file.

**Comment by rsraz** [comment]
Hi! sorry for the late reply actually I entered the correct code snippet I just made a mistake by including the instruction when I paste it here. But I pasted the exact code snippet there, but my PHP version that time was still 7.3 and I just recently updated it to 7.4 is there something to do with that? Thank you!

**Comment by danielbachhuber** [comment]
Hi @rsraz,

It looks like the exact problem of your fatal error is that the plugin doesn't exist at the specified directory:

```
require_once(): Failed opening required '/home1/vibesphc/public_html/internships/wp-content/plugins/wp-native-php-sessions/pantheon-sessions.php' (include_path='.:/opt/cpanel/ea-php73/root/usr/share/pear') in /home1/vibesphc/public_html/internships/wp-content/mu-plugins/000-loader.php on line 2
```

The code snippet you added to the mu-plugin is trying to load the plugin from this path: `/wp-content/plugins/wp-native-php-sessions/pantheon-sessions.php`.

It seems like you might've installed the plugin from the GitHub download feature, which put the plugin at this path: `/wp-content/plugins/wp-native-php-sessions-master/`. Notice the extra `-master` in the directory name.

I'd recommend installing WP Native PHP Sessions from the WordPress.org ZIP, and removing the GitHub download version. Once you do, the fatal error should go away.

**Comment by rsraz** [comment]
After I remove the github download version and replacing it with the
wordpress.org zip file, do i need to put the code snippet back?

**Comment by danielbachhuber** [comment]
Yep, you'll still want the code snippet there.

**Comment by rsraz** [comment]
Okay, thank you! iIwill try to do what you said and will give an update
asap.

**Comment by rsraz** [comment]
I made the changes and so far I haven't encountered any issues yet
