### ISSUE TITLE
"wp_pantheon_sessions" has no primary key (error when migrating/restoring using UpdraftPlus)

### ISSUE THREAD

**Issue by Thomas-1985** [pantheon-systems/wp-native-php-sessions#170]
Hi

I am using the latest version of the plugin (1.2.1) with WordPress 5.5.1

During restore/migration of a website with UpdraftPlus, i am getting lots of messages like:
---
Fehler: "wp_pantheon_sessions" has no primary key, manual change needed on row 3759.
Fehler: "wp_pantheon_sessions" has no primary key, manual change needed on row 3848.
Fehler: "wp_pantheon_sessions" has no primary key, manual change needed on row 3871.
Fehler: "wp_pantheon_sessions" has no primary key, manual change needed on row 4075.
Fehler: "wp_pantheon_sessions" has no primary key, manual change needed on row 4095.
Fehler: "wp_pantheon_sessions" has no primary key, manual change needed on row 4129.
Fehler: "wp_pantheon_sessions" has no primary key, manual change needed on row 4151.
Fehler: "wp_pantheon_sessions" has no primary key, manual change needed on row 4186.
Fehler: "wp_pantheon_sessions" has no primary key, manual change needed on row 4196.
Fehler: "wp_pantheon_sessions" has no primary key, manual change needed on row 4376.
Fehler: "wp_pantheon_sessions" has no primary key, manual change needed on row 4469.
Fehler: "wp_pantheon_sessions" has no primary key, manual change needed on row 4638.
Fehler: "wp_pantheon_sessions" has no primary key, manual change needed on row 4647.
Fehler: "wp_pantheon_sessions" has no primary key, manual change needed on row 4700.
Fehler: "wp_pantheon_sessions" has no primary key, manual change needed on row 4788.
Fehler: "wp_pantheon_sessions" has no primary key, manual change needed on row 4812.
Fehler: "wp_pantheon_sessions" has no primary key, manual change needed on row 4829.
Fehler: "wp_pantheon_sessions" has no primary key, manual change needed on row 4844.
Fehler: "wp_pantheon_sessions" has no primary key, manual change needed on row 4896.
---

Best,
Thomas

**Comment by danielbachhuber** [comment]
Hi @Thomas-1985,

You'll either need to:

1. Add a primary key to the `wp_pantheon_sessions` table.
2. Delete and recreate the table from scratch.

**Comment by Thomas-1985** [comment]
Hi

Is this maybe a bug in the plugin during creation? Has it been fixed?
