### ISSUE TITLE
Plugin not working on local environment

### ISSUE THREAD

**Issue by silvio-gratani** [pantheon-systems/wp-native-php-sessions#177]
Hi, i'm planning to to port a website i'm working on to a balanced architecture and found this (seems to be) promising plugin.

I've installed it in my local enviroment as simple plugin at first, not as a mu-plugin, and see that db table is correctly created, but when visiting the site (any page) no record is written in the table, it stills empty.

So i installed it as a mu-plugin, but the db table stills empty.

There is no configuration page from the admin panel, so i can't figure out how to use it.

Do i need to do something more to get it working?

**Comment by danielbachhuber** [comment]
Hi @silvio-gratani,

Sorry to hear you're having troubles.

> I've installed it in my local enviroment as simple plugin at first, not as a mu-plugin, and see that db table is correctly created, but when visiting the site (any page) no record is written in the table, it stills empty.

Data will only be written to the database when it's first written to a `$_SESSION`. Can you share the code you're using that interacts with sessions?

**Comment by scottbuscemi** [comment]
Closing due to age, feel free to re-open if this is still needed.
