### ISSUE TITLE
[question] Are old sessions cleared in the database?

### ISSUE THREAD

**Issue by Lakro** [pantheon-systems/wp-native-php-sessions#179]
Hi,

very nice and useful Plugin. Exact what we had been looking for.

I would like to know if old sessions are ceaned up from the database?
Maybe in a regular way and if, - after how many days?

We are just testing the plugin and the sessions are stored for now 6 days in the database?

Or do we have to do anything on ourself ...?

(I only found one issue from 2017 where you refered to an additonalplugin but that plugin does not longer exist: #62)

Thx for your answer.

Best Regards
Lakro

**Comment by danielbachhuber** [comment]
Hi @Lakro,

> I would like to know if old sessions are ceaned up from the database?
Maybe in a regular way and if, - after how many days?

Yes, they're cleaned up in the database using PHP's standard garbage collection mechanism. You can read more about it here: https://www.php.net/manual/en/function.session-gc.php

It looks like the default garbage collection is 24 minutes: https://www.php.net/manual/en/session.configuration.php#ini.session.gc-maxlifetime

If you're finding that your sessions aren't being cleaned up, you might want to follow some of those directions to enable regular garbage collection.

Note though, the session is kept around as long as the user is active on the site. Here's our underlying implementation:

https://github.com/pantheon-systems/wp-native-php-sessions/blob/48131e2d968f7a581dcd0d069264c0238ae32f32/inc/class-session-handler.php#L98-L110

**Comment by Lakro** [comment]
Thx for the Information. Helped a lot and to solve/understand the problem.

Following additional information could be interesting to you support or others who have the same problem in future:

**If found this hint in web:**

Some [webserver-]distributions change the cleanup mechanism, for example Debian/Ubuntu flavored PHP versions set session.gc_probability=0 and use a cronjob to cleanup old session data. ([Source](https://tideways.com/profiler/blog/php-session-garbage-collection-the-unknown-performance-bottleneck))

Indeed on my testing server the session.gc_probability has been set to 0 ... and the cronjob on the server didn't go together with the plugin in wordpress (which needs to cleanup the wp database) and of course did not do the job in wordpress. 

Changing the settings in the php.ini to standard solved the problem in MY case:

```
session.gc_probability = 1;
session.gc_divisor = 100;

; Hints: 
; for TESTING ONLY you can set 'session.gc_divisor = 1'
; on live systems values for probability and divisor should be scaled to your traffic!
```

Best Regards 
Lakro

**Comment by danielbachhuber** [comment]
Glad you were able to figure it out! And thanks for following up with the additional detail 😄
