### ISSUE TITLE
Sessions not starting in a VVV setup

### ISSUE THREAD

**Issue by magbicaleman** [pantheon-systems/wp-native-php-sessions#18]
I originally believed this to be a VVV environment configuration issue, but it turns out after **deactivating** [this](https://github.com/pantheon-systems/wp-native-php-sessions) plugin and adding the code below to the wp-config-local.php, the session_id stopped changing after every refresh and the session variable set in a functions was usable after it redirected to another page on the same domain.

Previously I was hooking into an action and setting a session variable, but when the page was redirected the $_SESSION super global was NULL. 

``` php
if (!session_id())
    session_start();
```

I'm not sure if the code below is the way that you use this particular plugin, or if there is a static function call or what not.

``` php
$_SESSION['sample'] = true 
```

[Original Issue](https://github.com/Varying-Vagrant-Vagrants/VVV/issues/749)

**Comment by joshkoenig** [comment]
Just to be clear: you have the plugin turned on, and then some code that bootstraps WP and does something like:

```
$_SESSION['sample'] = true;
```

And then you are not able to hit another page powered by WP and see the session value? Are you seeing any session cookie or data in the `pantheon_sessions` table?

Just for kicks, what about some test code like this:

```
$sess_val = 'set-at-' . time();
$_SESSION[$sess_val] = "I made this";
var_dump($_SESSION);
```

You should see it build up a bunch of session values for each page refresh.

**Comment by magbicaleman** [comment]
@joshkoenig correct.

In the themes/THEME/function.php I have the following;
```php
add_filter( 'gform_confirmation', 'custom_confirmation', 10, 4 );

function custom_confirmation( $confirmation, $form, $entry, $ajax ) {
  $_SESSION['entry-id'] = s2member_encrypt($entry['id']);
  return $confirmation;
}
```
With the plugin activated, once the page redirects to it's proper location the $_SESSION super global is NULL when var_dump();

--

Checking the *wp_pantheon_sessions* there are two rows, but none of which contain any new $_SESSION set by the function above.

--

I added the code you provided above on the page in which the function above redirects to. It then display the following below.
```php
array(1) { ["set-at-1443208358"]=> string(11) "I made this" }
```

This code also did not create a new row in the  *wp_pantheon_sessions*  table.

**Comment by joshkoenig** [comment]
Ok then it's for-sure not starting any sessions. I don't have a VVV setup that's healthy right now, but can try to get one going to replicate and debug.

**Comment by nicdev** [comment]
@joshkoenig I ran into a similar issue where EventEspresso 4 wasn't saving registrations to session. Turning off Pantheon sessions fixed it. I'm not using VVV, just a plain Vagrant running Ubuntu 14.

**Comment by joshkoenig** [comment]
@nicdev gonna break that into it's own issue if you don't mind.
