### ISSUE TITLE
[question] Session stored unencrypted

### ISSUE THREAD

**Issue by Lakro** [pantheon-systems/wp-native-php-sessions#180]
Hi,

there is just another question:

Testing the plugin we saw, that the content of the sessions are stored to database in a unencrypted way.

Maybe: 
Is there a way to encrypt that in an automatic way by the plugin? 

Why: 
According to the stored content it maybe could become a Data Security Conflict with DSGVO in Europe?

Thx and best regards
Lakro

**Comment by danielbachhuber** [comment]
Hi @Lakro,

We don't currently support any form of data encryption. If this is a requirement for your site, you'll need to encrypt the data before it's included in the session.
