### ISSUE TITLE
How can I check if a session variable exists without starting a session ?

### ISSUE THREAD

**Issue by bilalhassan** [pantheon-systems/wp-native-php-sessions#22]
Not sure if a silly question or not, however here's my issue:

I am using a plugin that uses sessions for authenticating users ( not WP User ),

following WP guidelines to session_start() in an init hook, 
I need to check if a user is authenticated before a start a session, otherwise based on the init hook, session_start() will run for every user, even if they are not authenticated, and im trying to reduce the number of sessions being created.

Do you have any suggestions as to how to access the session array without having to run session_start() for every user ?

**Comment by danielbachhuber** [comment]
Based on a quick Google, I came across this suggestion: http://stackoverflow.com/a/18542272

Would that check work for you?

**Comment by joshkoenig** [comment]
Yep. That's the right answer. Use `session_status()` if at all possible:

http://php.net/manual/en/function.session-status.php

If that says "no session" then you know the value can't be there. If it says, "session exists" then there's no harm in doing an `isset($_SESSION['my_var'])` to see whether a value is present.
