### ISSUE TITLE
Deprecated notice in Wordpress 6.1.1

### ISSUE THREAD

**Issue by aboutzahurul** [pantheon-systems/wp-native-php-sessions#230]
Getting Deprecated notice in WordPress 6.1.1 with WP_DEBUG enabled and PHP version 8.1.13

Deprecated: Return type of Pantheon_Sessions\Session_Handler::close() should either be compatible with SessionHandlerInterface::close(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /wp-content/plugins/wp-native-php-sessions/inc/class-session-handler.php on line 122

**Comment by jspellman814** [comment]
As noted in #231: this has been incorporated into version 1.3.3 of the plugin (related [commit](https://github.com/pantheon-systems/wp-native-php-sessions/pull/232/commits/686c179f3594145d806b7d5ab5b4262496a03db1)). Please update and let us know if you have any further issues.

**Comment by jazzsequence** [comment]
Closing as resolved in #231. If this issue persists, please re-open & let us know.
