### ISSUE TITLE
[BUGS-6643] Formatting issue

### ISSUE THREAD

**Issue by amboutwe** [pantheon-systems/wp-native-php-sessions#261]
The heading for 'Contributing' is mistakenly part of the code snippet when viewed on WordPress.org [here](https://wordpress.org/plugins/wp-native-php-sessions/).

It's possible that this is due to how WP processes and converts the readme (not a dev so just a guess) as the lower code doesn't have the same issue. However, the lower code is followed by a paragraph which made me first guess it might be a WP conversion issue. A quick workaround, if that is the case, would be to add a short paragraph or break between the code and heading.

![screenshot_065](https://github.com/pantheon-systems/wp-native-php-sessions/assets/8060612/805a473b-7f6a-49e9-ab58-57d70fe0b5e6)

**Comment by jazzsequence** [comment]
Thanks for catching this! This is indeed a weird one, because the readme looks fine otherwise. 

Tracking it internally as BUGS-6643

**Comment by jazzsequence** [comment]
This was actually fixed in 1.3.6 but we never closed out this issue.
