### ISSUE TITLE
Conflicts with configuring CAS login

### ISSUE THREAD

**Issue by ttrowell** [pantheon-systems/wp-native-php-sessions#27]
"I have three sites hosted on Pantheon and all are effected by this issue. I am trying to implement a CAS login set up on my wordpress sites that will work with my University's CAS system. I have been trying implement this since the end of last year and have not gotten anywhere. I have bee n working with my IT department and we have it narrowed down. It seems that a plug in that I have installed "Native PHP Sessions" is the culprit. This is a plug in that is from Pantheon and I need it to run my site. I can't even disable it. The plugin I am trying to use to enable CAS is "UTHSC WPCAS". We have tested it on another host and server and it works fine until you add "Native PHP Sessions" by Pantheon. If you could share any solutions you may have so that I can enable CAS I am open."  

issue desk#56181

**Comment by danielbachhuber** [comment]
@ttrowell Were you able to track down any more details on the specific nature of the conflict? It would be helpful to know what specifically doesn't work when both plugins are activated together.

**Comment by achbed** [comment]
There are some issues with the UTHSC WPCAS plugin that make it difficult to interact cleanly with WP Native PHP Sessions [WNPS] (and hosting platforms like Pantheon).  

It looks like the WPCAS starts the configuration process during the initial class creation, before WNPS is initialized.  This means that it stores data in $_SESSION before we even get the chance to begin, and when we start we blow away that data.

Also, it appears that the CAS library used writes data to its own set of files or database tables.  I also don't see anywhere in the WPCAS plugin where it sets any kind of database configuration, so it's using the default file system data store (as defined by session_save_path before we touch it).

There are quite a few fixes that need to be made before the WPCAS plugin can work with WNPS, or in a hosting configuration like Pantheon.  There's not much we can with in this plugin to fix those deficiencies.

@danielbachhuber do you concur?

**Comment by danielbachhuber** [comment]
> It looks like the WPCAS starts the configuration process during the initial class creation, before WNPS is initialized. This means that it stores data in $_SESSION before we even get the chance to begin, and when we start we blow away that data.

To work around this, you could install WPNS as a mu plugin, to ensure it's always loaded before any other plugin. In fact, we should probably recommend this as the preferred installation method.

> Also, it appears that the CAS library used writes data to its own set of files or database tables. I also don't see anywhere in the WPCAS plugin where it sets any kind of database configuration, so it's using the default file system data store (as defined by session_save_path before we touch it).

How does this impact WPNS?

> There are quite a few fixes that need to be made before the WPCAS plugin can work with WNPS, or in a hosting configuration like Pantheon. There's not much we can with in this plugin to fix those deficiencies.

Without reviewing the WPCAS plugin myself, it's hard to make this assessment. But, I do agree generally.

**Comment by achbed** [comment]
> How does this impact WPNS?
It doesn't.  We are not defining `session_save_path()` - it uses the PHP setting.  This is a design deficit with the other plugin, not something we can fix.

She should try installing this plugin as a `mu` plugin.  If that doesn't solve the problem, then the UTHSC WPCAS plugin maintainer should be notified of compatibility issues with Pantheon (and similar) hosting.

**Comment by danielbachhuber** [comment]
Thanks for clarifying, @achbed.

@ttrowell Let us know if there's anything else we can help with on this thread.
