### ISSUE TITLE
Release v0.5.0

### ISSUE THREAD

**Issue by danielbachhuber** [pantheon-systems/wp-native-php-sessions#29]
* [x] Update changelog with the changes.
* [x] Refresh readme.txt
* [ ] Tag release on WordPress.org
* [ ] Tag release on Github

**Comment by danielbachhuber** [comment]
:ship:

**Comment by danielbachhuber** [comment]
@joshkoenig ^ FYI

**Comment by joshkoenig** [comment]
Woot!
