### ISSUE TITLE
Is this plugin still maintained?

### ISSUE THREAD

**Issue by tedw** [pantheon-systems/wp-native-php-sessions#292]
Hi there, just wondering if this plugin is still maintained. The WP plugin page currently shows this warning:

>This plugin hasn’t been tested with the latest 3 major releases of WordPress. It may no longer be maintained or supported and may have compatibility issues when used with more recent versions of WordPress.

https://wordpress.org/plugins/wp-native-php-sessions/

**Comment by pwtyler** [comment]
Hi there, updates are infrequent, but yes, this is still maintained. We've just updated CI so we can get a readme update to wp.org without cutting a release, and updated "Tested Up To" at https://wordpress.org/plugins/wp-native-php-sessions/.

**Comment by tedw** [comment]
@pwtyler Awesome, thank you!
