### ISSUE TITLE
Configure WP Coding Standards PHP sniffs

### ISSUE THREAD

**Issue by danielbachhuber** [pantheon-systems/wp-native-php-sessions#32]
Our other Pantheon plugins have them, so this one should have them too.

**Comment by luyendao** [comment]
Hi Daniel - wondering if you could chime in. I'm using PHP Sessions to store a user's visit to certain pages on my site, the problem I get using native PHP sessions with Wordpress (without your code) is the sessions seem to get cached in the production environment (goes through an HTTP proxy) but no other caching mechanism.

Is this something this code can help with?

**Comment by graogd** [comment]
I am using session for paid users subscription in wordpress, when I am using php native session the loading time very slow , i am using pantheon environment for my site. When I am disabled php native session plugin the speed looks fine..is there any solution this any or any alter methods. We are facing loading issues complete site.
