### ISSUE TITLE
Suggest changing Plugin URI to https://github.com/pantheon-systems/wp-native-php-sessions

### ISSUE THREAD

**Issue by slashzero** [pantheon-systems/wp-native-php-sessions#44]
Currently, the Plugin URI is set to https://www.pantheon.io, this should be changed to the Github URI https://github.com/pantheon-systems/wp-native-php-sessions.

**Comment by danielbachhuber** [comment]
@slashzero I think [standard practice](https://codex.wordpress.org/File_Header#Plugin_File_Header_Example) is actually to use the WordPress.org directory URL. What do you think about this?

**Comment by slashzero** [comment]
LGTM, happy to go with standard practice.
