### ISSUE TITLE
Any support for wp_cache functions?

### ISSUE THREAD

**Issue by yombo** [pantheon-systems/wp-native-php-sessions#50]
We use redis as our object cache. Any thoughts about a selection between DB and Object cache? This might speed things up and lessen the load on the SQL servers.

**Comment by danielbachhuber** [comment]
Interesting idea, certainly!

If implemented, we'd probably want to connect directly to Redis instead of attempting to rely on the object cache.

**Comment by yombo** [comment]
It looks like phpredis has support for this: https://github.com/phpredis/phpredis

Unless you want to add support for this for people that can't run phpredis, looks like we can close this issue.

Edit the php.ini file:
session.save_handler = redis
session.save_path = "tcp://host1:6379?weight=1, tcp://host2:6379?weight=2&timeout=2.5, tcp://host3:6379?weight=2"

**Comment by danielbachhuber** [comment]
> It looks like phpredis has support for this: https://github.com/phpredis/phpredis

Oh, neat!

> Unless you want to add support for this for people that can't run phpredis, looks like we can close this issue.

I don't know that it's necessary to support this within the plugin, but we could mention it in the README. Up for submitting a PR with instructions?

**Comment by leventmuslim** [comment]
I apologise for re-opening an old subject if incase this is improper. Adding my question below this felt right to extend the topic a little more and to seal it for good

I've been using wp-native-php-sessions plugin for a while and recently changed php.ini settings to;
session.save_handler = redis
session.save_path = "tcp://127.0.0.1:6379"

Is it still okay to keep wnps activated? 
Is it going to somewhow begin using redis database or should I disable wpns from now on?

**Comment by danielbachhuber** [comment]
@leventmuslim No worries! If you're using `session.save_handler = redis`, then you shouldn't need WP Native PHP Sessions. In fact, you'll need to deactivate WP Native PHP Sessions in order to use Redis as your session store.

**Comment by leventmuslim** [comment]
Okay thank you for answering, I'll deactivate as your suggestion. It's been a major and helpful plugin it'll be sad not seeing it on the plugins menu.
