### ISSUE TITLE
Feature Request DynamoDB storage option

### ISSUE THREAD

**Issue by nueverest** [pantheon-systems/wp-native-php-sessions#58]
It seems Amazon has documented a way to use DynamoDB for session storage.

https://aws.amazon.com/blogs/aws/scalable-session-handling-in-php-using-amazon-dynamodb/

How hard would it be add a setting or option for this?

**Comment by danielbachhuber** [comment]
Thanks for the feature request, @nueverest. Unfortunately, this request is outside the scope of the project. WP Native PHP Sessions uses the `$wpdb` connection exclusively.
