### ISSUE TITLE
[question] Are old/stale sessions cleared from the database?

### ISSUE THREAD

**Issue by ollietreend** [pantheon-systems/wp-native-php-sessions#62]
I'm interested to know if there's any housekeeping performed on the database to clean out old and stale sessions.

If not, this seems like a task that could be handled with a regular WP Cron task.

Is database clean-up already handled by this plugin?

**Comment by danielbachhuber** [comment]
> Is database clean-up already handled by this plugin?

Yes, database cleanup happens in this garbage collection callback: https://github.com/pantheon-systems/wp-native-php-sessions/blob/master/callbacks.php#L138-L156
