### ISSUE TITLE
Tighten up the test that indicates if a plugin is using PHP Sessions

### ISSUE THREAD

**Issue by ttrowell** [pantheon-systems/wp-native-php-sessions#63]
Feature Request / Minor bug fix request: Tighten up the test that indicates if a plugin is using PHP Sessions.

The WP-GeoMeta plugin includes some some tests which output formatted SQL. The SQL formatter includes an array of reserved words in SQL, including the word 'SESSION'. 

https://wordpress.org/plugins/wp-geometa/

I get the "You should install the Native PHP Sessions plugin" warning when using this plugin, even though it doesn't do anything use 'session_start()', $_SESSION, etc. It just has the string 'SESSION'. 

If you don't want to install the actual plugin, you can see the code here:

https://github.com/BrilliantPlugins/wp-geometa-lib/blob/54dbc7d6b47243c5f1f34c591f89ef949a167aa5/test/tests/__SqlFormatter.php

Search for 'SESSION' and you'll find the strings 'SESSION' and 'SESSION_USER'.

**Comment by danielbachhuber** [comment]
Hi @ttrowell,

This plugin doesn't actually do any code scanning for strings. Did you mean to open this issue in WP Launch Check? https://github.com/pantheon-systems/wp_launch_check/issues

Here's the regex used in WP Launch check: https://github.com/pantheon-systems/wp_launch_check/blob/a9cf15a04b0fac82965bcefa77dc13e4e3beaf90/php/pantheon/checks/sessions.php#L24

**Comment by danielbachhuber** [comment]
This was fixed by https://github.com/pantheon-systems/wp_launch_check/pull/46
