### ISSUE TITLE
No primary key cause problems with db replication

### ISSUE THREAD

**Issue by enricodeleo** [pantheon-systems/wp-native-php-sessions#64]
Moving from single-instance db to a new replicated environment I got this error during import: 
```
ERROR 3098 (HY000) at line 271: The table does not comply with the requirements by an external plugin
```
 
After some research I found this [great article](http://lefred.be/content/mysql-group-replication-and-table-design/) that helped me find the issue (and cause): apparently the table created by this plugin doesn't set a primary key and this prevent it to be used in such an environment. 
I can confirm the error because excluding just `wp_pantheon_sessions` from the export I could import it seamlessy.

**Comment by danielbachhuber** [comment]
> Moving from single-instance db to a new replicated environment I got this error during import:

Was this error solely when you were importing the database into the environment, or were the slaves giving this error as you replicated?

> After some research I found this great article that helped me find the issue (and cause): apparently the table created by this plugin doesn't set a primary key

This is correct: 841f15f21d707b9f2988359e663b1970f7beab01

I believe I simply copied Drupal's schema for sessions.

> I can confirm the error because excluding just `wp_pantheon_sessions` from the export I could import it seamlessy.

After you imported, did the plugin then recreate the table and function as expected?

**Comment by enricodeleo** [comment]
Thank you for the reply @danielbachhuber.
I'm trying to move to compose for mysql by IBM that is kind of a black box at the moment (nor UI is provided neither status about replication). What I can see, accessing the endpoint via `mysql` is that the table is empty.

![image](https://cloud.githubusercontent.com/assets/3534555/25911579/ae14dbca-35b4-11e7-9870-52cc17434e7e.png)
