### ISSUE TITLE
Session creation not handling boolean conditions

### ISSUE THREAD

**Issue by dustinleblanc** [pantheon-systems/wp-native-php-sessions#74]
Customer is seeing this:

> Error: 
> Uncaught Error: Call to a member function set_data() on boolean in /srv/bindings/REDACTED/code/wp-content/plugins/wp-native-php-sessions/callbacks.php:100 Stack trace: #0 [internal function]: _pantheon_session_write(REDACTED) #1 /srv/bindings/REDACTED/code/wp-includes/class-wp-hook.php(296): session_write_close() #2 /srv/bindings/REDACTED/code/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters(NULL, Array) #3 /srv/bindings/REDACTED/code/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #4 /srv/bindings/REDACTED/code/wp-includes/load.php(677): do_action('shutdown') #5 [internal function]: shutdown_action_hook() #6 {main} thrown 

In their error logs. Looking at the code at https://github.com/pantheon-systems/wp-native-php-sessions/blob/master/callbacks.php#L100

I'd imagine that the two possible session get/create functions preceding this should throw exceptions rather than return a boolean if they do not successfully return a session object. Barring that being possible, before trying set the data, we could explicitly check that the session is a properly constructed object.

**Comment by danielbachhuber** [comment]
@dustinleblanc I've just pushed [v0.6.3](https://github.com/pantheon-systems/wp-native-php-sessions/releases/tag/v0.6.3) which includes a fix for this.
