### ISSUE TITLE
Check for existence of admin class file in case it's not included.

### ISSUE THREAD

**Issue by pderksen** [pantheon-systems/wp-native-php-sessions#83]
Some plugins would like to include the entire WP Native PHP Sessions plugin inside their own. See #81.

But they don't necessarily need the admin UI functionality of it, so `inc/class-admin.php` & `inc/class-list-table.php` can be safely removed.

However, we need a `file_exists` check so the code that attempts to include them doesn't cause an error.

**Comment by danielbachhuber** [comment]
See https://github.com/pantheon-systems/wp-native-php-sessions/issues/81#issuecomment-350736058
