### ISSUE TITLE
On some hosts getting: Warning: ini_set(): A session is active.

### ISSUE THREAD

**Issue by pderksen** [pantheon-systems/wp-native-php-sessions#84]
Getting this only on some hosts so far.

Warning: ini_set(): A session is active. You cannot change the session module's ini settings at this time.

Pointing to this line in https://github.com/pantheon-systems/wp-native-php-sessions/blob/master/pantheon-sessions.php#L119

`ini_set( 'session.use_trans_sid', '0' );`

I also have this in my plugin code:

```
if ( ! session_id() && ! headers_sent() ) {
	session_start();
}
```

Should I be making additional checks or changes when starting a session?

Thanks!

**Comment by danielbachhuber** [comment]
> Getting this only on some hosts so far.

Couple of follow-up questions:

* Are these stock WordPress installs, with no additional plugins active and a Twenty* theme installed?
* Can you figure out what the PHP configuration differences are between the hosts with the error and the hosts without?

> Should I be making additional checks or changes when starting a session?

What you've shared seems like it should work to me.

**Comment by pderksen** [comment]
@danielbachhuber On one site it was a conflict with the [RegistrationMagic](https://wordpress.org/plugins/custom-registration-form-builder-with-submission-manager/).

It looks like they also have the call:
```
if( !session_id() )
     session_start();
```

Going to do some more digging.

**Comment by pderksen** [comment]
@danielbachhuber It doesn't look like it's an issue with your plugin after all.

The way I tried to implement it within my own plugin ignores the ["force first load"](https://github.com/pantheon-systems/wp-native-php-sessions/blob/master/pantheon-sessions.php#L189-L213) technique you're using, so when another plugin does a `session_start()` this error message pops up.

I'll need to figure a workaround for our use case but you can close this as needed. Thanks again!

**Comment by danielbachhuber** [comment]
👌

**Comment by johnnysurf** [comment]
Just curious.  Running into the same issue on Pantheon.  Would loading pantheon-sessions as an mu-plugin fix these types of issues?

**Comment by danielbachhuber** [comment]
> Would loading pantheon-sessions as an mu-plugin fix these types of issues?

Possibly. Loading `pantheon-sessions` as a mu-plugin is the recommended approach.

**Comment by johnnysurf** [comment]
Sounds good.  I'll try that approach.  Thanks for your quick feedback Daniel!
