### ISSUE TITLE
Version 0.6.5 causes Pantheon DB clone process to fail at the URL replacement stage

### ISSUE THREAD

**Issue by johndotcocking** [pantheon-systems/wp-native-php-sessions#86]
The logfiles for this are not available to users, only to Pantheon staff, but you can see the error messages for yourself by:
1) Getting a job at Pantheon ;-)
or 
2) Installing version 0.6.5 of the plugin, cloning the DB without search/replace, then running this terminus command against your site:
terminus wp [site-name].[environment-name] -- search-replace "://[production-url]" "://[dev-url]"

We got an error on session_start() that user session functions are not defined.

**Comment by danielbachhuber** [comment]
Thanks for the report, @johndotcocking.

The genesis of this would be #85. However, although the behavior has changed, I almost think the _current_ behavior (error on `session_start()`) is the correct behavior. Sessions shouldn't be started in CLI context.

Is it possible for you to call `session_start()` only in the non-CLI context?

**Comment by johndotcocking** [comment]
Thanks, @danielbachhuber That works for me for now.
It looks like my long-term fix is to get a better understanding of Pantheon's systems work together. Thankfully, I have a lot of documentation at my disposal!

**Comment by danielbachhuber** [comment]
Sounds good, thanks @johndotcocking
