### ISSUE TITLE
Handle a failed database connection better. 

### ISSUE THREAD

**Issue by smartcatdev** [pantheon-systems/wp-native-php-sessions#9]
The plugin throws this error every once in a while, and that has caused my site to go down twice in the past week since I have put it live.

I am running WordPress with a custom theme that utilises WordPress sessions.

In both situations, the service rep had to restart the services on the site so it comes back up.

Screenshot
![image](https://cloud.githubusercontent.com/assets/3696057/5170233/21c5ed68-73dc-11e4-9de0-309f82fd2c0c.png)

**Comment by rdanamcd** [comment]
I just had this exact same error 5 times on the live site. I'm thinking I'll just temporarily add on line 23 class-session.php: if ( !isset( $wpdb ) ) { return false; }. Would that keep this from happening again?

Thanks
Dana
pif.today

![screen shot 2016-01-24 at 7 04 58 am](https://cloud.githubusercontent.com/assets/5899832/12536136/7b718836-c269-11e5-91b7-ba5acd165363.png)

**Comment by danielbachhuber** [comment]
@rdanamcd Can you share any plugins you might be running which could be nullifying the `$wpdb` global?

**Comment by rdanamcd** [comment]
I have your plugin in the mu-plugins folder. It runs first. Not quite sure how I would find what would have nullified it. It's working now and the error is not consistent. I thought it was related when I cleared all my cookies in the browser but can't reproduce. It might have been a temp connection issue in Pantheon. Not sure. I'll keep an eye on if it does it again.

**Comment by danielbachhuber** [comment]
This issue was caused by #56
