### ISSUE TITLE
Disable sessions for REST request

### ISSUE THREAD

**Issue by lougreenwood** [pantheon-systems/wp-native-php-sessions#90]
Hi,

I'm attempting to disable sessions for WP REST requests. I've tried hooking into `rest_api_init` and destroying sessions from there, but it seems to have no effect.

Any suggestion on how to achieve this? Here's what I've attempted so far...

```
/**
 * Don't use PHP session if in REST.

 */
add_action( 'rest_api_init', function()
	{
		if( session_id() )
		{
			require_once( WP_PLUGIN_DIR.'/wp-native-php-sessions/inc/class-session.php');
			$session = \Pantheon_Sessions::get_instance();
			if( $session )
			{
				$session->delete_cookies();
				$session->destroy();
			}
		}

		define( PANTHEON_SESSIONS_ENABLED, false );
	}
);
```

Also, what are your thoughts on whether to include something like this in the plugin - in the same way that sessions are disabled for WP CLI?
As far as I understand, session state violates the concept of a RESTful API, so it should theoretically be safe to disable sessions here and keep within the spirit of a proper RESTful implementation...

**Comment by danielbachhuber** [comment]
Interesting question, @lougreenwood — thanks for opening the conversation.

> I'm attempting to disable sessions for WP REST requests. I've tried hooking into `rest_api_init` and destroying sessions from there, but it seems to have no effect.

As soon as you call `session_start()`, PHP emits the session cookie. You can destroy the session when the REST API is initialized, but it won't have destroyed the cookie already emitted. I think you'd need to intercept much earlier.

> Also, what are your thoughts on whether to include something like this in the plugin - in the same way that sessions are disabled for WP CLI?

If we can find a robust implementation, we can certainly consider it.

> As far as I understand, session state violates the concept of a RESTful API, so it should theoretically be safe to disable sessions here and keep within the spirit of a proper RESTful implementation...

I agree... however, unlike with WP-CLI, there's not a reliable way (to my knowledge) of knowing whether a request is a REST API request at the point of the plugin loading. Do you know of one?

And, taking a step back, have you found some practical problem, or is this more of a theoretical concern?
