### ISSUE TITLE
Fails on Install on Pantheon

### ISSUE THREAD

**Issue by wpropel** [pantheon-systems/wp-native-php-sessions#94]
Fails to activate on Pantheon with the following:

Fatal error: Cannot declare class Pantheon_Sessions, because the name is already in use in /srv/bindings/e495cf9dc1b440bbbe418e11c78b95bc/code/wp-content/plugins/wp-native-php-sessions/pantheon-sessions.php on line 17

**Comment by danielbachhuber** [comment]
Hi @wpropel,

Thanks for the report! This issue is most likely due to how you've configured the plugin with your site.

Can you open a ticket with Pantheon support and they'll help you sort it out?
