### ISSUE TITLE
_pantheon_session_write tries to trigger E_WARNING - should be E_USER_WARNING instead?

### ISSUE THREAD

**Issue by PabloWestphalen** [pantheon-systems/wp-native-php-sessions#96]
Was experimenting with sessions,  broke things along the way and when the plugin tried to trigger this neat little warning

trigger_error( 'Could not write session to the database. Please check MySQL configuration.', E_WARNING );

i got a warning from PHP (7.1) instead saying that E_WARNING was not a valid error to trigger

**Comment by danielbachhuber** [comment]
Thanks for the report, @PabloWestphalen! I'll tag a release for this shortly.
